"""added user object and auth providers for odic providers

Revision ID: 225b89a508dd
Revises: 6814dc8e5e30
Create Date: 2026-08-02 20:31:58.854880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225b89a508dd'
down_revision: Union[str, Sequence[str], None] = '6814dc8e5e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
