"""rename board object date to data

Revision ID: b0591cc37bf7
Revises: 329b947f2a7f
Create Date: 2026-07-31 20:12:30.237065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0591cc37bf7'
down_revision: Union[str, Sequence[str], None] = '329b947f2a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_objects', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('board_objects', 'date')
    op.alter_column('boards', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boards', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('board_objects', sa.Column('date', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('board_objects', 'data')
    # ### end Alembic commands ###
